name: ASP.NET Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup .NET Environment
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0' # Justera versionen efter ditt behov
        
    - name: Restore NuGet Packages
      run: dotnet restore
      
    - name: Build Solution
      run: dotnet build --configuration Release
      
    - name: Test Solution
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish Artifact
      uses: actions/upload-artifact@v2
      with:
        name: drop
        path: '**/bin/Release/**' # Justera sökvägen baserat på dina projekt
